name: mps-youtube
base: core18
version: 'git'
summary: Terminal based YouTube player and downloader
description: |
  This project is based on mps, a terminal based program to search, stream
  and download music. This implementation uses YouTube as a source of
  content and can play and download video as well as audio. The pafy library
  handles interfacing with YouTube.

grade: stable
confinement: strict

parts:
  mps-youtube:
    plugin: python
    source: .
    stage-packages:
      - mpv

apps:
  mps-youtube:
    command: bin/mpsyt
    plugs:
      - home
      - network
      - pulseaudio
